#!/usr/bin/env bash
# release.sh — BasePod TestFlight リリース ワンショット
#
# 動作:
#   1. (Web) pnpm build → out/ static export 生成
#   2. (Web) npx cap sync ios → ios/App/App/public/ にコピー
#   3. (Native) project.pbxproj の CURRENT_PROJECT_VERSION を +1
#   4. (Native) Info.plist CFBundleVersion を pbxproj 値で同期 (xcvar 展開後の保険)
#   5. (C6 Sim) 起動 + screenshot + ios_app_validator.sh で plist レイヤー診断
#   6. (Native) xcodebuild archive (Cloud signing で Distribution profile 自動取得)
#   7. (Native) xcodebuild -exportArchive (.ipa 出力)
#   8. (Validate) ios_app_validator.sh --ipa で配信前最終検証 (HR-13)
#   9. (Upload) xcrun altool --upload-app (App Store Connect upload)
#
# 前提:
#   - Apple Developer Identifiers で App ID `jp.base393.BasePod` 登録済み
#   - App Store Connect で App `BasePod` 作成済み
#   - ~/.appstoreconnect/private_keys/AuthKey_<KEY_ID>.p8 配置済み (権限 Admin)
#   - 環境変数 API_KEY_ID / API_KEY_ISSUER 設定済み
#     (または scripts/release.env に記述済み、.gitignore 対象)
#   - pnpm 10 系 + Node 22 系 + Capacitor 8 + Xcode (cap sync 可能)
#
# Usage:
#   bash scripts/release.sh                  # フル実行 (Web build → archive → upload)
#   SKIP_WEB_BUILD=1 bash scripts/release.sh # Web build スキップ (直前流用)
#   SKIP_C6_SIM=1 bash scripts/release.sh    # C6 Sim 検証スキップ (非推奨)

set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$PROJECT_DIR"

IOS_DIR="$PROJECT_DIR/ios/App"
PBXPROJ="$IOS_DIR/App.xcodeproj/project.pbxproj"
INFO_PLIST="$IOS_DIR/App/Info.plist"
EXPORT_OPTIONS="$PROJECT_DIR/Configuration/ExportOptions-iOS.plist"

ARCHIVE_PATH="/tmp/BasePod-iOS.xcarchive"
EXPORT_PATH="/tmp/BasePod-iOS-export"
SIM_BUILD_DIR="/tmp/BasePod-Sim"
SIM_DEVICE="${SIM_DEVICE:-iPhone 17 Pro}"

# === Secret 取得 ===
# 環境変数優先、未設定時は scripts/release.env から source
if [ -z "${API_KEY_ID:-}" ] || [ -z "${API_KEY_ISSUER:-}" ]; then
  if [ -r "scripts/release.env" ]; then
    # shellcheck disable=SC1091
    source scripts/release.env
  fi
fi

if [ -z "${API_KEY_ID:-}" ] || [ -z "${API_KEY_ISSUER:-}" ]; then
  cat >&2 <<EOF
ERROR: API_KEY_ID と API_KEY_ISSUER が未設定。

設定方法 (いずれか):
  A) 環境変数で渡す:
     export API_KEY_ID=XXXXXXXXXX
     export API_KEY_ISSUER=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
     bash scripts/release.sh

  B) scripts/release.env を作成 (.gitignore 対象):
     cp scripts/release.env.example scripts/release.env
     # release.env を編集して値を埋める
     chmod 600 scripts/release.env
     bash scripts/release.sh

API Key の発行: https://appstoreconnect.apple.com → ユーザーとアクセス → 統合
EOF
  exit 1
fi

API_KEY_PATH="$HOME/.appstoreconnect/private_keys/AuthKey_${API_KEY_ID}.p8"
if [ ! -r "$API_KEY_PATH" ]; then
  echo "ERROR: API key file not found: $API_KEY_PATH" >&2
  echo "       App Store Connect で発行した .p8 を上記パスに配置してください" >&2
  exit 1
fi

# === 必要ツール存在確認 ===
need_tool() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "ERROR: required tool not found: $1" >&2
    exit 1
  fi
}
need_tool xcodebuild
need_tool xcrun
need_tool /usr/libexec/PlistBuddy
if [ "${SKIP_WEB_BUILD:-0}" != "1" ]; then
  need_tool pnpm
  need_tool npx
fi

# === Step 1-2: Web build + cap sync ===
if [ "${SKIP_WEB_BUILD:-0}" = "1" ]; then
  echo "==> SKIP_WEB_BUILD=1 → pnpm build / cap sync をスキップ"
else
  echo ""
  echo "============================================"
  echo "==> Web build (pnpm build → out/ static export)"
  echo "============================================"
  pnpm build

  if [ ! -d "$PROJECT_DIR/out" ]; then
    echo "ERROR: out/ directory not generated by pnpm build" >&2
    exit 1
  fi

  echo ""
  echo "==> Capacitor sync (out/ → ios/App/App/public/)"
  npx cap sync ios
fi

# === Step 3: Build番号インクリメント (pbxproj 直接) ===
# pbxproj 内の CURRENT_PROJECT_VERSION を全部 +1
# (Capacitor 生成 pbxproj は Debug/Release で同値、複数行に同値が入っている)
CURRENT_BUILD=$(grep -E "CURRENT_PROJECT_VERSION = [0-9]+;" "$PBXPROJ" \
  | head -1 | sed -E 's/.*CURRENT_PROJECT_VERSION = ([0-9]+);.*/\1/')
if [ -z "$CURRENT_BUILD" ]; then
  echo "ERROR: CURRENT_PROJECT_VERSION not found in $PBXPROJ" >&2
  exit 1
fi
NEW_BUILD=$((CURRENT_BUILD + 1))
echo ""
echo "==> Build number: $CURRENT_BUILD → $NEW_BUILD"

sed -i.bak -E "s/CURRENT_PROJECT_VERSION = ${CURRENT_BUILD};/CURRENT_PROJECT_VERSION = ${NEW_BUILD};/g" "$PBXPROJ"
rm -f "${PBXPROJ}.bak"

# === Step 4: Info.plist CFBundleVersion 同期 ===
# Capacitor の Info.plist は $(CURRENT_PROJECT_VERSION) で xcvar 展開されるため
# 通常は不要だが、過去に BaseBrowser で発生した「pbxproj と plist のズレ」を
# 構造的に防ぐため保険として明示同期する (literal の場合も対応)。
CURRENT_PLIST_VAL=$(/usr/libexec/PlistBuddy -c "Print :CFBundleVersion" "$INFO_PLIST" 2>/dev/null || echo "")
if [ "$CURRENT_PLIST_VAL" != '$(CURRENT_PROJECT_VERSION)' ] && [ -n "$CURRENT_PLIST_VAL" ]; then
  /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $NEW_BUILD" "$INFO_PLIST"
  echo "==> CFBundleVersion → $NEW_BUILD (Info.plist literal 上書き)"
else
  echo "==> CFBundleVersion: \$(CURRENT_PROJECT_VERSION) を維持 (xcvar 展開で $NEW_BUILD)"
fi

# === Step 5: C6 Sim 検証 (起動 + screenshot + validator) ===
# HR-12/HR-13: archive 前に Sim 起動できるか + plist レイヤーが揃っているかを確認。
# Phase 1/2/A/B (BaseBrowser 2026-05-04) で発生した「Sim 検証短絡 → 実機 NG」を
# 構造的に防ぐ。SKIP_C6_SIM=1 で迂回可能だが非推奨。
VALIDATOR="$HOME/Library/CloudStorage/GoogleDrive-akira_s@393base.jp/マイドライブ/_Claude/04_tools/ios_app_validator.sh"

if [ "${SKIP_C6_SIM:-0}" = "1" ]; then
  echo ""
  echo "==> SKIP_C6_SIM=1 → Sim 検証をスキップ (非推奨)"
else
  echo ""
  echo "============================================"
  echo "==> C6 Sim 検証 (build + screenshot + validator)"
  echo "============================================"
  rm -rf "$SIM_BUILD_DIR"

  # Sim build (signing 不要、起動可否判定のため)
  set +e
  xcodebuild -project "$IOS_DIR/App.xcodeproj" \
    -scheme "App" \
    -configuration Debug \
    -destination "platform=iOS Simulator,name=${SIM_DEVICE}" \
    -derivedDataPath "$SIM_BUILD_DIR" \
    CODE_SIGNING_ALLOWED=NO \
    build 2>&1 | grep -E "(error|warning|BUILD|SUCCEEDED|FAILED)" | tail -10
  SIM_BUILD_RC=${PIPESTATUS[0]}
  set -e
  if [ "$SIM_BUILD_RC" -ne 0 ]; then
    echo "ERROR: Sim build FAILED (exit $SIM_BUILD_RC)、archive 中止" >&2
    exit 1
  fi

  # Sim 上の .app を validator にかける (plist 必須キー検証)
  SIM_APP=$(find "$SIM_BUILD_DIR/Build/Products" -maxdepth 4 -type d -name "App.app" | head -1)
  if [ -n "$SIM_APP" ] && [ -x "$VALIDATOR" ]; then
    echo ""
    echo "==> ios_app_validator.sh --app (pre-archive plist 検証)"
    set +e
    bash "$VALIDATOR" --app "$SIM_APP"
    V_RC=$?
    set -e
    if [ "$V_RC" -ge 2 ]; then
      echo "ERROR: pre-archive validator FAIL (exit $V_RC)、archive 中止" >&2
      exit 1
    elif [ "$V_RC" -ge 1 ]; then
      echo "WARN: pre-archive validator WARN (exit $V_RC)、継続" >&2
    fi
  elif [ ! -x "$VALIDATOR" ]; then
    echo "WARN: validator not found at $VALIDATOR、pre-archive 検証スキップ" >&2
  else
    echo "WARN: Sim .app が見つからない、pre-archive 検証スキップ" >&2
  fi
fi

# === Step 6: Archive ===
echo ""
echo "============================================"
echo "==> Archive (build $NEW_BUILD)"
echo "============================================"
rm -rf "$ARCHIVE_PATH" "$EXPORT_PATH"

xcodebuild -project "$IOS_DIR/App.xcodeproj" \
  -scheme "App" \
  -destination "generic/platform=iOS" \
  -archivePath "$ARCHIVE_PATH" \
  -allowProvisioningUpdates \
  -allowProvisioningDeviceRegistration \
  -authenticationKeyPath "$API_KEY_PATH" \
  -authenticationKeyID "$API_KEY_ID" \
  -authenticationKeyIssuerID "$API_KEY_ISSUER" \
  ${DEVELOPMENT_TEAM:+DEVELOPMENT_TEAM="$DEVELOPMENT_TEAM"} \
  archive 2>&1 | grep -E "(error|warning|ARCHIVE|SUCCEEDED|FAILED)" | tail -10

if [ ! -d "$ARCHIVE_PATH" ]; then
  echo "ERROR: archive not generated at $ARCHIVE_PATH" >&2
  exit 1
fi

# === Step 7: Export (.ipa) ===
echo ""
echo "==> Export (.ipa)"
xcodebuild -exportArchive \
  -archivePath "$ARCHIVE_PATH" \
  -exportPath "$EXPORT_PATH" \
  -exportOptionsPlist "$EXPORT_OPTIONS" \
  -allowProvisioningUpdates \
  -allowProvisioningDeviceRegistration \
  -authenticationKeyPath "$API_KEY_PATH" \
  -authenticationKeyID "$API_KEY_ID" \
  -authenticationKeyIssuerID "$API_KEY_ISSUER" \
  2>&1 | tail -5

# Capacitor scheme は "App" なので artifact 名は App.ipa になる
IPA_FILE=$(find "$EXPORT_PATH" -maxdepth 2 -name "*.ipa" | head -1)
if [ -z "$IPA_FILE" ] || [ ! -f "$IPA_FILE" ]; then
  echo "ERROR: ipa not found in $EXPORT_PATH" >&2
  exit 1
fi
echo "==> IPA: $IPA_FILE"

# === Step 8: HR-13 配信前 validator (ipa 直接) ===
if [ -x "$VALIDATOR" ]; then
  echo ""
  echo "==> HR-13 validator --ipa (配信前最終検証)"
  set +e
  bash "$VALIDATOR" --ipa "$IPA_FILE"
  V_RC=$?
  set -e
  if [ "$V_RC" -ge 2 ]; then
    echo "ERROR: HR-13 validator FAIL (exit $V_RC)、配信中止" >&2
    exit 1
  elif [ "$V_RC" -ge 1 ]; then
    echo "WARN: HR-13 validator WARN (exit $V_RC)、配信継続" >&2
  fi
else
  echo "WARN: HR-13 validator not found at $VALIDATOR、配信前検証スキップ" >&2
fi

# === Step 9: altool upload (env 渡し / HR-14 漏洩防止) ===
# HR-14: --apiKey/--apiIssuer をコマンドライン引数に出すと `ps aux` で漏洩する。
# altool は環境変数 API_PRIVATE_KEYS_DIR / API_KEY_ID / API_ISSUER_ID を解釈するが、
# 移行期で fallback も必要なため env 渡し + 引数の両構えにする。
echo ""
echo "==> Upload to App Store Connect"
API_PRIVATE_KEYS_DIR="$HOME/.appstoreconnect/private_keys" \
API_KEY_ID="$API_KEY_ID" \
API_ISSUER_ID="$API_KEY_ISSUER" \
xcrun altool --upload-app \
  -f "$IPA_FILE" \
  --type ios \
  --apiKey "$API_KEY_ID" \
  --apiIssuer "$API_KEY_ISSUER"

echo ""
echo "============================================"
echo "✓ Release flow completed (build $NEW_BUILD)"
echo "  TestFlight processing: 数分〜数十分"
echo "  確認: https://appstoreconnect.apple.com/ → BasePod → TestFlight"
echo "============================================"
